;
; This example code illustrates how to access and visualize an NSIDC MODIS 25km
; LAMAZ (EASE) Grid file in IDL.  EASE stands for "Equal-Area, Spherical Earth"
; See reference [1], below.  The EASE map projection is the same as the Lambert
; Azimuthal projection, known as "LAMAZ" to EOS.
;
; If you have any questions, suggestions, comments on this example, please use
;  the HDF-EOS Forum (http://hdfeos.org/forums).
;
; If you would like to see an example of any other NASA HDF/HDF-EOS data
;  product that is not listed in the HDF-EOS Comprehensive Examples page
;  (http://hdfeos.org/zoo), feel free to contact us at  eoshelp@hdfgroup.org
; or post it at the HDF-EOS Forum (http://hdfeos.org/forums).
;
; Tested under: IDL 8.0
; Last updated: 2012-12-18

; Define  the file name, grid name, and data field name.
FILE_NAME='AMSR_E_L3_5DaySnow_V09_20050126.hdf'
GRID_NAME='Northern Hemisphere'
DATAFIELD_NAME='SWE_NorthernPentad'

; This data file has no 'units' attribute. Set it manually [1].
unit='mm'

; This data file has no 'long_name' attribute. Set it manually [1].
long_name = GRID_NAME + ' 5-Day Snow Water Equivalent'

; Open file via the EOS_GD interface.
file_id = EOS_GD_OPEN(FILE_NAME)

; Attach to the named grid.
grid_id = EOS_GD_ATTACH(file_id, GRID_NAME)

; Retrieve data via the EOS_GD interface
status = EOS_GD_READFIELD(grid_id, DATAFIELD_NAME, data)

; Detach from the grid.
status = EOS_GD_DETACH(grid_id)

; Close the EOS_GD interface to the file.
status = EOS_GD_CLOSE(file_id)

; The map projection for the data grid is Lambert Azimuthal (LAMAZ)
; In this example, we used the EOS2 Dumper generate 1D lat and lon.
; For information on how to obtain the lat/lon data, see reference [2], below.

; get the data field dimensions
dimsize=size(data,/dim)
numlat=dimsize(0)
numlon=dimsize(1)

; Open the ASCII geolocation file and read the latitude data into a 1-D array.
LAT_FILENAME='lat_AMSR_E_L3_5DaySnow_V09_20050126.Northern_Hemisphere.output'
openr,1,LAT_FILENAME
size=numlat*numlon
ValInlat=FltArr(size)
READF,1,ValInlat
close,1

; Open the ASCII geolocation file and read the longitude data into a 1-D array.
LON_FILENAME='lon_AMSR_E_L3_5DaySnow_V09_20050126.Northern_Hemisphere.output'
openr,2,LON_FILENAME
size=numlat*numlon
ValInlon=FltArr(size)
READF,2,ValInlon
close,2

; Reform the lat/lon arrays to 2-D grids of same dimensions as the data field.
lat=FINDGEN(numlat,numlon)
lat=REFORM(ValInlat,numlat,numlon)

lon=FINDGEN(numlat,numlon)
lon=REFORM(ValInlon,numlat,numlon)

; Generate the plot.
DEVICE, DECOMPOSED=0

;  The following key information for color table is obtained from the
; AMSR-E/Aqua L3 Global Snow Water Equivalent data product description at:
;  http://nsidc.org/data/docs/daac/ae_swe_ease-grids.gd.html#format
; Data values: 0-240 SWE divided by 2 (mm)
;                241 non-validated
;                247 incorrect spacecraft attitude
;                248 off-earth
;                252 land or snow impossible
;                253 ice sheet
;                254 water
;                255 missing
;
;  We'll use 0-240 values only.
dataf = FLOAT(data)
idx=WHERE(dataf GT 240, cnt)
IF cnt GT 0 THEN dataf[idx] = !Values.F_NAN
; Multiply by two according to data spec [1].
dataf = 2 * dataf 

; Get max and min value of data for color bar.
datamin = MIN(dataf, /NAN)
datamax = MAX(dataf, /NAN)



; Limit the plot to the Northern Hemisphere.
;
; This LAMAZ projection data spans over -90 to 90 and -180 and 180.
; To get a zoomed effect, MAP_SET LIMIT option the lat max to -30
latmin=0
latmax=90
lonmin=-180
lonmax=180

; Generate a plot.
levels = 254
DEVICE, DECOMPOSED=0
LOADCT, 33, NCOLORS=levels, BOTTOM=1
WINDOW, TITLE='FIELD:' +  long_name + 'UNITS:' + unit
; LAMBERT Azimuthal Projection with origin at the North pole (90 lat)
; The /ISOTROPIC option makes the plot square.
MAP_SET, /LAMBERT, 90, 0, 0, /ISOTROPIC, /CONTINENTS, XMARGIN=5, YMARGIN=5, $
 POSITION=[0.05, 0.05, 0.82, 0.82], LIMIT=[latmin, lonmin, latmax, lonmax]
; Generate the filled contour plot
; CONTOUR, dataf, lon, lat, /OVERPLOT, /CELL_FILL, Background=1, NLEVELS=levels,$
;         Color=Black, C_COLORS=Indgen(levels)+1
CONTOUR, dataf, lon, lat, /OVERPLOT, /CELL_FILL, C_COLORS=INDGEN(levels)+3, $
  NLEVELS=levels

; Don't use /BOX_GRID option for polar view.
MAP_GRID, /LABEL
MAP_CONTINENTS
XYOuts, 0.45, 0.84, /Normal, 'FIELD:' + long_name, $
  Charsize=1.25, Alignment=0.5
XYOuts, 0.95, 0.84, /Normal, 'UNITS:' + unit, $
  Charsize=1.25, Alignment=1.0
XYOuts, 0.5, 0.92, /Normal, FILE_NAME, $
  Charsize=1.75,  Alignment=0.5

;  The following code is prepared for colorbar.
;
;   If you require colorbar in your plot, you could download
; "Dr. Fanning's Coyote Library" from reference [3], below.
; Make a directory named coyote somewhere on your machine,
; and extract the Coyote files into it.
;
;   If color bar is not not necessary for your plot, you can ignore this
; step and add comment character ';' ahead of coding.
;
;    Add the coyote directory you create on your machine to your IDL
;  path like below:
;
; !PATH=Expand_Path('[coyote directory on your machine])+':'+!PATH

; Let's assume that you've installed coyote library under the current working
; directory that this code exists.
!PATH=Expand_Path('+coyote/')+':'+!PATH

COLORBAR, RANGE=[datamin, datamax], NCOLORS=levels, /VERTICAL, $
 POSITION=[0.9,0.05,0.94,0.8]

; Write JPEG image file.
im = TVRD(TRUE=3)
jpg = file_name + '.idl.jpg'   
WRITE_JPEG, jpg, im, QUALITY=100, TRUE=3
EXIT

; References
;
; [1] AMSR-E/Aqua 5-Day L3 Global Snow Water Equivalent EASE-Grids
;     http://nsidc.org/cgi-bin/get_metadata.pl?id=ae_5dsno
;     http://nsidc.org/data/docs/daac/ae_swe_ease-grids.gd.html#format
; [2] http://hdfeos.org/zoo/note_non_geographic.php
; [3] http://www.dfanning.com/documents/programs.html

