;
;  This example code illustrates how to access and visualize LaRC MISR
; AM1 CGAL HDF-EOS2 Grid file in IDL. 
;
; If you have any questions, suggestions, comments  on this example, 
; please use the HDF-EOS Forum (http://hdfeos.org/forums).
;
;  If you would like to see an  example of any other NASA HDF/HDF-EOS 
; data product that is not listed in the HDF-EOS Comprehensive Examples page
; (http://hdfeos.org/zoo), feel free to contact us at eoshelp@hdfgroup.org
; or post it at the HDF-EOS Forum (http://hdfeos.org/forums).
;
; Usage:
;
;  $idl MISR_AM1_CGAL_2017_F06_0024.hdf.idl
;
; Tested under: IDL 8.6.0
; Last updated: 2018-08-14


; Define file name, grid name, and data field name.
FILE_NAME='MISR_AM1_CGAL_2017_F06_0024.hdf'
GRID_NAME='AlbedoAverage_1_degree'
DATAFIELD_NAME='Local albedo average - 1 deg'

; Open file.
file_id = EOS_GD_OPEN(FILE_NAME)

; Retrieve data.
grid_id = EOS_GD_ATTACH(file_id, GRID_NAME)
status = EOS_GD_READFIELD(grid_id, DATAFIELD_NAME, data)
status = EOS_GD_GETFILLVALUE(grid_id, DATAFIELD_NAME, fill_value)
status = EOS_GD_GRIDINFO(grid_id, xdimsize, ydimsize, upleft, lowright)
status = EOS_GD_PIXREGINFO(grid_id, pixregcode)
; Close file.
status = EOS_GD_DETACH(grid_id)
status = EOS_GD_CLOSE(file_id)

; There are two ways to compute lat, lon.
; First, use the specification.
; See the page p.264 of "MISR Data Products Specifications rev S" [1].
; lat= FINDGEN(180)*(-1)+89.5
; lon= FINDGEN(360)*1-179.5

; However, the following will be more general approach.
; We assume that HDFE_CENTER is 0 by default. See GDdefpixreg() in 
; "HDF-EOS Library Users Guide for the ECS Project Volume 2: Function
; Reference Guide".
IF (pixregcode EQ 1) THEN PRINT, 'ERROR:Pixel is not centered.' 
IF (pixregcode EQ 1) THEN EXIT

; Pixel must be centered.
offsetX = 0.5
offsetY = 0.5

; We need to readjust the limits of latitude and longitude. 
; HDF-EOS is using DMS(DDDMMMSSS.SS) format to represent degrees.
; So to calculate the lat and lon in degree, one needs to convert minutes and seconds into degrees. 

; The following is the detailed description on how to calculate the
; latitude  and longitude range based on lowright and upleft.
; One should observe the fact that 1 minute is 60 seconds and 1 degree 
; is 60 minutes. 

; First calculate the difference of .SS between lowright and upleft.
; Since the resulting number is very large, you need to specify /L64.
lowright_ss= lowright*100-FLOOR(lowright, /L64)*100
upleft_ss = upleft*100-FLOOR(upleft, /L64)*100;
dss = lowright_ss - upleft_ss;

; Then calculate the difference of SSS between lowright and upleft:
lowright_s = floor(lowright) MOD 1000
upleft_s = floor(upleft) MOD 1000

ds = lowright_s - upleft_s +dss/100;

; Then calculate the difference of MMM between lowright and upleft:
lowright_m = floor(lowright/1000) MOD 1000
upleft_m = floor(upleft/1000) MOD 1000

dm = lowright_m-upleft_m +ds/60;

; Then calculate the difference of DDD between lowright and upleft:
lowright_d = floor(lowright/1000000)
upleft_d = floor(upleft/1000000)
dd = lowright_d-upleft_d+dm/60

lat_limit = dd(1);
lon_limit = dd(0);

; We need to calculate the grid space interval between two adjacent points
scaleX = lon_limit/xdimsize
scaleY = lat_limit/ydimsize

lon_value= FINDGEN(xdimsize)
lat_value= FINDGEN(ydimsize)
for i=0,xdimsize-1 do lon_value(i) = (i+offsetX)*(scaleX) + upleft_d(0);
for j=0,ydimsize-1 do lat_value(j) = (j+offsetX)*(scaleY) + upleft_d(1);

lon = float(lon_value)
lat = float(lat_value)

; Convert the M-D lat to 2D lat at Band=3
data2D=data[3,*,*]
data2D=reform(data2D)

; Convert data type
data2D=float(data2D)
fill_value=float(fill_value)

;get max and min value of data
idx=where(data2D ne fill_value, cnt)
if cnt gt 0 then datamin=min(data2D[idx])
if cnt gt 0 then datamax=max(data2D[idx])

; Process fillvalue, convert data that are equal to fillvalue to NaN
idx=where(data2D eq fill_value, cnt)
if cnt gt 0 then data2D[idx] = !Values.F_NAN

; Generate the plot.
m = MAP('Geographic', TITLE=file_name, FONT_SIZE=9, /BUFFER)
ct = COLORTABLE(72, /reverse)

; IRREGULAR must be used.
c1 = CONTOUR(data2D, lon, lat, /FILL, /IRREGULAR, OVERPLOT=m, $
             RGB_TABLE=ct, $
             GRID_UNITS='degrees', POSITION=[0.1, 0.1, 0.83, 0.9])
mc = MAPCONTINENTS()
long_name = DATAFIELD_NAME+' at Band=3'
t1 = TEXT(0.01, 0.05, FONT_SIZE=8, long_name)
units = 'No Unit'
cb = COLORBAR(TARGET=c1, /BORDER, ORIENTATION=1, $
              TEXTPOS=1, POSITION=[0.85,0.3,0.87,0.7], TITLE=units)
png = file_name + '.idl.png'
c1.save, png, WIDTH=800, HEIGHT=600
EXIT
; References
;
; [1] https://asdc.larc.nasa.gov/documents/misr/DPS_v50_RevS.pdf

